package hu.bitraptors.fazakas.homework.foursquare.model

data class VenueX(
    val attributes: Attributes,
    val beenHere: BeenHere,
    val bestPhoto: BestPhoto,
    val canonicalUrl: String,
    val categories: List<CategoryX>,
    val contact: Contact,
    val createdAt: Int,
    val description: String,
    val hereNow: HereNow,
    val hours: Hours,
    val id: String,
    val inbox: Inbox,
    val likes: Likes,
    val listed: Listed,
    val location: LocationX,
    val name: String,
    val page: Page,
    val pageUpdates: PageUpdates,
    val photos: Photos,
    val phrases: List<Phrase>,
    val popular: Popular,
    val rating: Double,
    val ratingColor: String,
    val ratingSignals: Int,
    val shortUrl: String,
    val stats: Stats,
    val storeId: String,
    val timeZone: String,
    val tips: TipsX,
    val url: String,
    val venueChains: List<Any>,
    val verified: Boolean
)